# Generated 2025-10-27 from:
# /kaggle/working/speechbrain/recipes/VoxCeleb/SpeakerRec/hparams/train_ecapa_tdnn.yaml
# yamllint disable
# ################################
# Model: Speaker identification with ECAPA
# Authors: Hwidong Na & Mirco Ravanelli
# ################################

# Basic parameters
seed: 1986
__set_seed: !apply:speechbrain.utils.seed_everything [1986]
# output_folder: 
#   1986_100
# save_folder: 
#   1986_100/save
# train_log: 
#   1986_100/train_log.txt

# Data for augmentation
NOISE_DATASET_URL: 
  https://www.dropbox.com/scl/fi/a09pj97s5ifan81dqhi4n/noises.zip?rlkey=j8b0n9kdjdr32o1f06t0cw5b7&dl=1
RIR_DATASET_URL: 
  https://www.dropbox.com/scl/fi/linhy77c36mu10965a836/RIRs.zip?rlkey=pg9cu8vrpn2u173vhiqyu743u&dl=1

# Data files
data_folder: /kaggle/input/vnceleb/dataset_region
data_folder_noise: /kaggle/input/vnceleb/dataset_region/noise
data_folder_rir: /kaggle/input/vnceleb/dataset_region/rir
# train_annotation: 
#   1986_100/save/train.csv
# valid_annotation: 
#   1986_100/save/dev.csv
# noise_annotation: 
#   1986_100/save/noise.csv
# rir_annotation: 
#   1986_100/save/rir.csv

verification_file: 
  https://www.robots.ox.ac.uk/~vgg/data/voxceleb/meta/veri_test2.txt

split_ratio: [90, 10]
skip_prep: true
ckpt_interval_minutes: 15

# Training parameters
number_of_epochs: 100
batch_size: 24
lr: 0.0005
base_lr: 0.00000001
max_lr: 0.0005
step_size: 65000
sample_rate: 16000
sentence_len: 3.0
shuffle: true
random_chunk: true

# Feature parameters
n_mels: 80
left_frames: 0
right_frames: 0
deltas: false

# Number of speakers
out_n_neurons: 11647

num_workers: 4
dataloader_options:
  batch_size: 24
  shuffle: true
  num_workers: 4

# Functions
compute_features: &id005 !new:speechbrain.lobes.features.Fbank
  n_mels: 80
  left_frames: 0
  right_frames: 0
  deltas: false

embedding_model: &id006 !new:speechbrain.lobes.models.ECAPA_TDNN.ECAPA_TDNN
  input_size: 80
  channels: [1024, 1024, 1024, 1024, 3072]
  kernel_sizes: [5, 3, 3, 3, 1]
  dilations: [1, 2, 3, 4, 1]
  groups: [1, 1, 1, 1, 1]
  attention_channels: 128
  lin_neurons: 192

classifier: &id007 !new:speechbrain.lobes.models.ECAPA_TDNN.Classifier
  input_size: 192
  out_neurons: 11647

epoch_counter: &id009 !new:speechbrain.utils.epoch_loop.EpochCounter
  limit: 100

############################## Augmentations ###################################

prepare_noise_data: !name:speechbrain.augment.preparation.prepare_dataset_from_URL
  URL: 
    https://www.dropbox.com/scl/fi/a09pj97s5ifan81dqhi4n/noises.zip?rlkey=j8b0n9kdjdr32o1f06t0cw5b7&dl=1
  dest_folder: /kaggle/input/vnceleb/dataset_region/noise
  ext: wav
  # csv_file: 
  #   1986_100/save/noise.csv

add_noise: &id001 !new:speechbrain.augment.time_domain.AddNoise
  # csv_file: 
  #   1986_100/save/noise.csv
  snr_low: 0
  snr_high: 15
  noise_sample_rate: 16000
  clean_sample_rate: 16000
  num_workers: 4

prepare_rir_data: !name:speechbrain.augment.preparation.prepare_dataset_from_URL
  URL: 
    https://www.dropbox.com/scl/fi/linhy77c36mu10965a836/RIRs.zip?rlkey=pg9cu8vrpn2u173vhiqyu743u&dl=1
  dest_folder: /kaggle/input/vnceleb/dataset_region/rir
  ext: wav
  csv_file: 
    1986_100/save/rir.csv

add_reverb: &id002 !new:speechbrain.augment.time_domain.AddReverb
  csv_file: 
    1986_100/save/rir.csv
  reverb_sample_rate: 16000
  clean_sample_rate: 16000
  num_workers: 4

drop_freq: &id003 !new:speechbrain.augment.time_domain.DropFreq
  drop_freq_low: 0
  drop_freq_high: 1
  drop_freq_count_low: 1
  drop_freq_count_high: 3
  drop_freq_width: 0.05

drop_chunk: &id004 !new:speechbrain.augment.time_domain.DropChunk
  drop_length_low: 1000
  drop_length_high: 2000
  drop_count_low: 1
  drop_count_high: 5

wav_augment: !new:speechbrain.augment.augmenter.Augmenter
  parallel_augment: true
  concat_original: true
  min_augmentations: 4
  max_augmentations: 4
  augment_prob: 1.0
  augmentations: [*id001, *id002, *id003, *id004]

mean_var_norm: &id008 !new:speechbrain.processing.features.InputNormalization

  norm_type: sentence
  std_norm: false

modules:
  compute_features: *id005
  embedding_model: *id006
  classifier: *id007
  mean_var_norm: *id008
compute_cost: !new:speechbrain.nnet.losses.LogSoftmaxWrapper
  loss_fn: !new:speechbrain.nnet.losses.AdditiveAngularMargin
    margin: 0.2
    scale: 30

opt_class: !name:torch.optim.Adam
  lr: 0.0005
  weight_decay: 0.000002

lr_annealing: &id010 !new:speechbrain.nnet.schedulers.CyclicLRScheduler
  base_lr: 0.00000001
  max_lr: 0.0005
  step_size: 65000

train_logger: !new:speechbrain.utils.train_logger.FileTrainLogger
  save_file: 
    1986_100/train_log.txt

error_stats: !name:speechbrain.utils.metric_stats.MetricStats
  metric: !name:speechbrain.nnet.losses.classification_error
    reduction: batch

checkpointer: !new:speechbrain.utils.checkpoints.Checkpointer
  checkpoints_dir: 
    ECAPA_TDNN
    # 1986_100/save
  recoverables:
    embedding_model: *id006
    classifier: *id007
    normalizer: *id008
    counter: *id009
    lr_annealing: *id010
